## Using CUDA

In [4]:
import torch
t = torch.tensor([1,2,3])
r = torch.tensor([4,5,6])
print(t)
print(r)

tensor([1, 2, 3])
tensor([4, 5, 6])


In [5]:
t = t.cuda()
t

tensor([1, 2, 3], device='cuda:0')

In [9]:
# r = r.to("cuda")
r = r.to(0)
r

tensor([4, 5, 6], device='cuda:0')

## Tensors

Ranks, Axes, Shape

The rank of a tensor refers to the number of dimensions present within the tensor. e.g. If we have rank2 tensor, it means:

-> Matrix, 2-D Array, 2-D Tensor

So we need 2 indices to access rank 2 tensors.


In [10]:
dd = [[1,2,3],
      [4,5,6],
      [7,8,9]]
dd

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
t = torch.tensor(dd)
t

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [12]:
type(t)

torch.Tensor

In [14]:
t.shape # Size and Shape are same in Pytorch

torch.Size([3, 3])

In [16]:
len(t.shape) # Rank of the tensor can be determined by tensor's shape

2

Reshaping

In [17]:
t.reshape(1,9) 

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [20]:
t.reshape(1,9).shape

torch.Size([1, 9])

In [21]:
r = torch.tensor(dd)
r

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [22]:
r.view(1,9)

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [24]:
r.view(1,9).shape

torch.Size([1, 9])