In [0]:
import torch
import torchvision

In [0]:
# 1-D Tensor 
a = torch.tensor([1,2,3])
print(a)

tensor([1, 2, 3])


In [0]:
# 2-D Tensor 
b = torch.tensor([[1,2,3,9],[4,5,6,9],[7,8,9,9]])
print(b)

tensor([[1, 2, 3, 9],
        [4, 5, 6, 9],
        [7, 8, 9, 9]])


In [0]:
# shape is an attribute and size is a function
print(a.shape)
print(b.shape)
print(a.size())
print(b.size())

torch.Size([3])
torch.Size([3, 4])
torch.Size([3])
torch.Size([3, 4])


In [0]:
# gives rows of b
print(b.shape[0])

3


In [0]:
# gives cols of b
print(b.shape[1])

4


In [0]:
c = torch.FloatTensor([1,2,3])
print(c)

tensor([1., 2., 3.])


In [0]:
c = torch.DoubleTensor([4,5,6])
print(c)

tensor([4., 5., 6.], dtype=torch.float64)


In [0]:
c = torch.tensor([11,12,13,14], dtype=torch.float64) # torch.double etc...
print(c) 

tensor([11., 12., 13., 14.], dtype=torch.float64)


In [0]:
print(c.dtype)

torch.float64


In [0]:
print(c.mean())

tensor(12.5000, dtype=torch.float64)


In [0]:
print(c.std())

tensor(1.2910, dtype=torch.float64)


In [0]:
print(b)

tensor([[1, 2, 3, 9],
        [4, 5, 6, 9],
        [7, 8, 9, 9]])


In [0]:
## view is a reshape function. -1 means that this function will infer number of elements of that dimension.
b.view(4,-1)

tensor([[1, 2, 3],
        [9, 4, 5],
        [6, 9, 7],
        [8, 9, 9]])

In [0]:
# converting into 1-D array
b.view(12)

tensor([1, 2, 3, 9, 4, 5, 6, 9, 7, 8, 9, 9])

In [0]:
b.view(1,-1) # one row, 12 cols

tensor([[1, 2, 3, 9, 4, 5, 6, 9, 7, 8, 9, 9]])

In [0]:
# 3-D Tensors (Channels, Rows, Columns)
three_dim = torch.randn(2,3,4) # normally distributed random numbers

In [0]:
three_dim

tensor([[[ 0.6907, -0.7588,  0.8542,  0.7780],
         [ 0.0597, -0.0205, -0.3878,  1.4182],
         [ 0.3086,  1.5226,  0.4214,  1.0445]],

        [[ 0.4110,  0.3413,  0.5403,  0.4733],
         [-0.9129,  0.2723, -0.5485,  0.6110],
         [ 1.9017, -0.1903,  0.1411, -0.7231]]])

In [0]:
three_dim.view(2,-1) # 2 rows and rest of the elements in cols

tensor([[ 0.6907, -0.7588,  0.8542,  0.7780,  0.0597, -0.0205, -0.3878,  1.4182,
          0.3086,  1.5226,  0.4214,  1.0445],
        [ 0.4110,  0.3413,  0.5403,  0.4733, -0.9129,  0.2723, -0.5485,  0.6110,
          1.9017, -0.1903,  0.1411, -0.7231]])

In [0]:
r2 = torch.rand(4,4)
print(r2)

tensor([[0.4566, 0.1953, 0.3729, 0.2253],
        [0.4062, 0.0737, 0.0322, 0.2043],
        [0.8346, 0.8099, 0.9606, 0.7899],
        [0.0140, 0.0123, 0.8935, 0.3223]])


In [0]:
# Create an array of 5 random integers from values b/w 6 and 9 (exclusive of 10)
in_array = torch.randint(6,10,(5,))
print(in_array)
print(in_array.dtype)

tensor([7, 8, 7, 8, 6])
torch.int64


In [0]:
# Create a 2-D Matrix of 5 random integers from values b/w 6 and 9 (exclusive of 10)
in_array2 = torch.randint(6,10,(3,3))
print(in_array2)

tensor([[6, 9, 9],
        [8, 7, 8],
        [6, 9, 8]])


In [0]:
# Get the number of elemets
print(torch.numel(in_array))
print(torch.numel(in_array2))

5
9


In [0]:
print(in_array.size())
print(in_array2.size())

torch.Size([5])
torch.Size([3, 3])


In [0]:
print(in_array.shape)
print(in_array2.shape)

torch.Size([5])
torch.Size([3, 3])


In [0]:
z = torch.zeros(3,3)
print(z)
o = torch.ones(3,3)
print(o)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [0]:
i = torch.eye(3,3)
print(i)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [0]:
# generate random numbers exactly of the same size of r2.
r2_like = torch.randn_like(r2, dtype=torch.double)
print(r2_like)

tensor([[-1.5362,  0.2929, -1.2548,  2.1962],
        [-0.2565, -1.0607,  2.1759,  1.0816],
        [-0.3651, -1.4252, -2.1648, -0.4579],
        [ 0.7705, -0.6142, -1.5969, -2.2058]], dtype=torch.float64)


In [0]:
# Add two tensors, make sure they are the same size and data type
add_result = torch.add(r2, r2_like)
print(add_result)

tensor([[-1.0796,  0.4883, -0.8820,  2.4215],
        [ 0.1498, -0.9870,  2.2081,  1.2858],
        [ 0.4695, -0.6153, -1.2042,  0.3320],
        [ 0.7845, -0.6018, -0.7034, -1.8834]], dtype=torch.float64)


In [0]:
# In-Place addition (change the value of r2)
r2.add_(r2_like)
print(r2) # Reassign to r2

tensor([[-1.0796,  0.4883, -0.8820,  2.4215],
        [ 0.1498, -0.9870,  2.2081,  1.2858],
        [ 0.4695, -0.6153, -1.2042,  0.3320],
        [ 0.7845, -0.6018, -0.7034, -1.8834]])


In [0]:
# Indexing
print(r2[:,1]) # print all the rows and 1st column
print(r2[:,:2]) # print all the rows and first 2 columns (exclusive of 2)
print(r2[:3,:]) # print first 3 rows and all the columns
num = r2[2,3] # gete a single number at this location
print(num)
print(num.item()) # Getting value from tensor
print(r2[2,:]) # print 3rd row and all the columns 

tensor([ 0.4883, -0.9870, -0.6153, -0.6018])
tensor([[-1.0796,  0.4883],
        [ 0.1498, -0.9870],
        [ 0.4695, -0.6153],
        [ 0.7845, -0.6018]])
tensor([[-1.0796,  0.4883, -0.8820,  2.4215],
        [ 0.1498, -0.9870,  2.2081,  1.2858],
        [ 0.4695, -0.6153, -1.2042,  0.3320]])
tensor(0.3320)
0.3319852650165558
tensor([ 0.4695, -0.6153, -1.2042,  0.3320])


In [3]:
# Sum across 2nd dimension
a = torch.tensor([[[1,2,3],[4,5,6]],[[11,12,13],[14,15,16]]])
a

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[11, 12, 13],
         [14, 15, 16]]])

In [4]:
torch.sum(a, dim=2)

tensor([[ 6, 15],
        [36, 45]])