In [0]:
from __future__ import print_function
import torch

An uninitialized matrix is declared, but does not contain definite known values before it is used. When an uninitialized matrix is created, whatever values were in the allocated memory at the time will appear as the initial values.

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[1.7349e-35, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 2.8026e-45],
        [0.0000e+00, 1.1210e-44, 0.0000e+00],
        [1.4013e-45, 0.0000e+00, 0.0000e+00]])


In [3]:
# Randomly initialized matrix
x = torch.rand(5, 3)
print(x)

tensor([[0.9589, 0.6597, 0.4053],
        [0.3958, 0.5353, 0.6825],
        [0.3054, 0.8019, 0.0388],
        [0.5813, 0.2291, 0.4710],
        [0.6221, 0.3578, 0.2836]])


In [4]:
# Matrix filled with zeros
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [8]:
# Difference b/w ones and new_ones

# defining the tensor along with device to run on. (Assuming CUDA hardware is available)
x = torch.rand(5, 3, device="cuda")

# new_ones() works with existing tensor. y will inherit the datatype from x and it will run on same device as defined in x
y = x.new_ones(2, 2)
print(y)

# defining tensor. By default it will run on CPU.
x = torch.ones(5, 3)
print(x)

tensor([[1., 1.],
        [1., 1.]], device='cuda:0')
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


ones() is used to define tensor with 1. (as shown in example) of given size and is not dependent on the existing tensor, whereas new_ones() works with existing tensor which inherits properties like datatype and device from existing tensor and define the tensor with given size.

In [9]:
# Construct a tensor directly from data
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [10]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.5838,  0.1624, -1.1032],
        [ 0.9579,  1.8300, -1.2211],
        [ 0.4142,  2.0283, -0.5329],
        [-1.5728,  0.5226,  1.2525],
        [ 0.2286, -0.8080, -0.4566]])


In [11]:
# Getting the size of tensor
print(x.size()) # It returns a tuple so it supports all tuple operations

torch.Size([5, 3])


In [12]:
# Add Operation
y = torch.rand(5, 3)
print(x + y)

tensor([[ 1.4925,  0.8180, -0.2510],
        [ 1.2211,  2.7747, -0.4055],
        [ 1.1970,  2.5302, -0.0076],
        [-1.4382,  0.9136,  1.4629],
        [ 1.1585, -0.2300,  0.2781]])


In [13]:
# 2nd syntax of adding
print(torch.add(x, y))

tensor([[ 1.4925,  0.8180, -0.2510],
        [ 1.2211,  2.7747, -0.4055],
        [ 1.1970,  2.5302, -0.0076],
        [-1.4382,  0.9136,  1.4629],
        [ 1.1585, -0.2300,  0.2781]])


In [14]:
# Providing an output tensor as argument
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 1.4925,  0.8180, -0.2510],
        [ 1.2211,  2.7747, -0.4055],
        [ 1.1970,  2.5302, -0.0076],
        [-1.4382,  0.9136,  1.4629],
        [ 1.1585, -0.2300,  0.2781]])


In [15]:
# In-Place addition
# adds x to y
y.add_(x)
print(y) # Overrided y

tensor([[ 1.4925,  0.8180, -0.2510],
        [ 1.2211,  2.7747, -0.4055],
        [ 1.1970,  2.5302, -0.0076],
        [-1.4382,  0.9136,  1.4629],
        [ 1.1585, -0.2300,  0.2781]])


Any operation that mutates a tensor in-place is post-fixed with an _. For example: x.copy_(y), x.t_(), will change x.

In [16]:
print(x[:, 1]) # print all rows of 2nd column

tensor([ 0.1624,  1.8300,  2.0283,  0.5226, -0.8080])


In [17]:
# Resizing: If you want to resize/reshape tensor, you can use torch.view:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(z)
print(x.size(), y.size(), z.size())

tensor([[-0.0898, -2.4871,  1.6693, -0.5620, -0.5889,  0.8019, -0.1296,  0.3073],
        [ 1.0804,  1.1956,  0.2550, -0.4503, -0.8278,  0.7601, -0.2550,  0.9187]])
torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [18]:
# If you have a one element tensor, use .item() to get the value as a Python number
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.1095])
0.10950557142496109


# Numpy Bridge
Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory locations (if the Torch Tensor is on CPU), and changing one will change the other.

### Converting a Torch Tensor to a NumPy Array

In [20]:
a = torch.ones(5)
print(a)

b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [21]:
# See how the numpy array changed in value.
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### Converting NumPy Array to Torch Tensor

In [22]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)


[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

# CUDA Tensors
Tensors can be moved onto any device using the .to method.

In [25]:
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([1.1095], device='cuda:0')
tensor([1.1095], dtype=torch.float64)
