In [1]:
import torch

In [5]:
# 1-D Tensor/Vector
x = torch.empty(3)
x

tensor([-5.8865e+23,  4.5642e-41, -5.8865e+23])

In [6]:
# 2-D Tensor/Matrix
x = torch.empty(2,3)
x

tensor([[2.5878e-36, 0.0000e+00, 2.5862e-36],
        [0.0000e+00, 8.9683e-44, 0.0000e+00]])

In [7]:
# 3-D Tensor
x = torch.empty(2,2,3)
x

tensor([[[ 1.4013e-45,  0.0000e+00,  2.5883e-36],
         [ 0.0000e+00,  1.4013e-45,  0.0000e+00]],

        [[ 2.5882e-36,  0.0000e+00,  3.3631e-44],
         [ 0.0000e+00, -2.3198e+24,  4.5642e-41]]])

In [8]:
# 4-D Tensor
x = torch.empty(2,2,2,3)
x

tensor([[[[-5.8865e+23,  4.5642e-41,  2.5845e-36],
          [ 0.0000e+00,  4.4842e-44,  0.0000e+00]],

         [[ 2.9147e-43,  0.0000e+00, -3.1107e+08],
          [ 4.5642e-41,  0.0000e+00,  0.0000e+00]]],


        [[[ 1.4013e-45,  0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00]],

         [[ 0.0000e+00,  0.0000e+00,  2.5864e-36],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00]]]])

In [10]:
# Tensor with random values
x = torch.rand(2,2)
x

tensor([[0.4382, 0.6775],
        [0.3081, 0.2678]])

In [11]:
# Tensor with zeros
x = torch.zeros(2,2)
x

tensor([[0., 0.],
        [0., 0.]])

In [12]:
# Tensor with ones
x = torch.ones(2,2)
x

tensor([[1., 1.],
        [1., 1.]])

In [13]:
# Data Type
x.dtype

torch.float32

In [16]:
# Changing Torch dtype
x = torch.ones(2,2, dtype=torch.int)
y = torch.ones(2,2, dtype=torch.double)
print(x)
print(y)

tensor([[1, 1],
        [1, 1]], dtype=torch.int32)
tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)


In [17]:
# Size of Tensor
x.size() # rows,columns

torch.Size([2, 2])

In [18]:
# Python list to Tensors
x = torch.tensor([1,2,3,4])
x

tensor([1, 2, 3, 4])

## Basic Operations

In [39]:
x = torch.rand(2,2)
y = torch.rand(2,2)

In [40]:
print(x+y)
torch.add(x,y)

tensor([[0.6709, 0.7407],
        [1.1721, 1.1040]])


tensor([[0.6709, 0.7407],
        [1.1721, 1.1040]])

In [41]:
print(x-y)
torch.sub(x,y)

tensor([[-0.2032,  0.0801],
        [ 0.7685,  0.3903]])


tensor([[-0.2032,  0.0801],
        [ 0.7685,  0.3903]])

In [42]:
print(x*y)
torch.mul(x,y)

tensor([[0.1022, 0.1356],
        [0.1958, 0.2666]])


tensor([[0.1022, 0.1356],
        [0.1958, 0.2666]])

In [43]:
print(x/y)
torch.div(x,y)

tensor([[0.5350, 1.2425],
        [4.8091, 2.0937]])


tensor([[0.5350, 1.2425],
        [4.8091, 2.0937]])

In [45]:
# Inplace Addition to y
# same for other operations
y.add_(x)
print(y)

tensor([[0.9047, 1.1512],
        [2.1423, 1.8511]])


## Slicing

In [46]:
# Slicing is same as Python and Numpy

In [49]:
x = torch.rand(1)
x

tensor([0.6388])

In [52]:
# Get the value from a single tensor
# We can only use this when we have only one element in tensor
x.item()

0.6388151049613953

## Reshaping

In [53]:
x = torch.rand(4,4)
x

tensor([[0.9401, 0.0544, 0.0674, 0.4927],
        [0.0344, 0.5185, 0.8604, 0.7522],
        [0.2121, 0.6710, 0.0303, 0.8591],
        [0.1851, 0.0597, 0.7121, 0.0791]])

In [54]:
y = x.view(16)
y

tensor([0.9401, 0.0544, 0.0674, 0.4927, 0.0344, 0.5185, 0.8604, 0.7522, 0.2121,
        0.6710, 0.0303, 0.8591, 0.1851, 0.0597, 0.7121, 0.0791])

In [55]:
y = x.view(1,16)
y

tensor([[0.9401, 0.0544, 0.0674, 0.4927, 0.0344, 0.5185, 0.8604, 0.7522, 0.2121,
         0.6710, 0.0303, 0.8591, 0.1851, 0.0597, 0.7121, 0.0791]])

In [56]:
# Auto-detect one side of the size
z = x.view(-1,8)
z

tensor([[0.9401, 0.0544, 0.0674, 0.4927, 0.0344, 0.5185, 0.8604, 0.7522],
        [0.2121, 0.6710, 0.0303, 0.8591, 0.1851, 0.0597, 0.7121, 0.0791]])

## Numpy to Torch Tensor and Vice Versa

In [57]:
import numpy as np

In [59]:
a = torch.ones(5)
print(a)
print(type(a))
b = a.numpy()
print(b)
print(type(b))

tensor([1., 1., 1., 1., 1.])
<class 'torch.Tensor'>
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


#### If tensor is on CPU then both objects will use the same memory - hence, shallow copy

In [60]:
b[0] = 109
print(b)
print(a)

[109.   1.   1.   1.   1.]
tensor([109.,   1.,   1.,   1.,   1.])


In [61]:
a = np.ones(5)
print(a)
print(type(a))
b = torch.from_numpy(a)
print(b)
print(type(a))

[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
<class 'numpy.ndarray'>


In [62]:
a[0] = 99
print(a)
print(b)

[99.  1.  1.  1.  1.]
tensor([99.,  1.,  1.,  1.,  1.], dtype=torch.float64)


## Other

In [64]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    # Creating tensor on GPU
    x = torch.ones(5, device = device)
    print(x)
    y = torch.ones(5)
    # Move y to GPU
    y = y.to(device)
    print(y)
    print(x+y)
    z = y.numpy() # It will give an error. Because, Numpy can only handle CPU Tensors
    # To avoid that, we have to convert it into CPU
    z = y.to("cpu")
    
else:
    print("no")

no


In [ ]:
# It tells pytorch that it needs to calculate gradients for this tensor
# for optimization steps.
x = torch.rand(5, requires_grad=True) # By default its False
# Any variable that we need to optimize, we'll make this flag, True.