In [9]:
import torch
import torchvision
from torch.utils.data import Dataset, DataLoader
import numpy as np
import math

In [10]:
class WineDataset(Dataset):
    
    def __init__(self, transform=None):
        xy = np.loadtxt("./wine.csv", delimiter=',', dtype=np.float32, skiprows=1)
        self.x = xy[:,1:]
        self.y = xy[:,[0]] # (n_samples,1)
        self.n_samples = xy.shape[0]
        
        self.transform = transform
    
    def __getitem__(self, index):
        sample = self.x[index], self.y[index]
        
        if self.transform:
            sample = self.transform(sample)
            
        return sample
    
    def __len__(self):
        return self.n_samples

In [11]:
class ToTensor:
    def __call__(self,sample):
        inputs, targets = sample
        return torch.from_numpy(inputs), torch.from_numpy(targets)

In [18]:
class MulTransform:
    def __init__(self, factor):
        self.factor = factor
        
    def __call__(self, sample):
        inputs, targets = sample
        inputs *= self.factor
        
        return inputs, targets

In [19]:
dataset = WineDataset(transform=ToTensor())

In [20]:
dataset[0]

(tensor([1.4230e+01, 1.7100e+00, 2.4300e+00, 1.5600e+01, 1.2700e+02, 2.8000e+00,
         3.0600e+00, 2.8000e-01, 2.2900e+00, 5.6400e+00, 1.0400e+00, 3.9200e+00,
         1.0650e+03]),
 tensor([1.]))

In [22]:
composed = torchvision.transforms.Compose([ToTensor(),MulTransform(5)])

In [25]:
dataset = WineDataset(transform=composed)

In [26]:
dataset[0]

(tensor([7.1150e+01, 8.5500e+00, 1.2150e+01, 7.8000e+01, 6.3500e+02, 1.4000e+01,
         1.5300e+01, 1.4000e+00, 1.1450e+01, 2.8200e+01, 5.2000e+00, 1.9600e+01,
         5.3250e+03]),
 tensor([1.]))